version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: electron
    versions:
    - 11.2.1
    - 11.2.2
    - 11.2.3
    - 11.3.0
    - 12.0.0
    - 12.0.1
    - 12.0.2
    - 12.0.4
  - dependency-name: grunt-cli
    versions:
    - 1.3.2
    - 1.4.1
  - dependency-name: highcharts
    versions:
    - 8.2.2
    - 9.0.0
  - dependency-name: grunt
    versions:
    - 1.3.0
  - dependency-name: menubar
    versions:
    - 5.2.3
  - dependency-name: grunt-contrib-less
    versions:
    - 2.0.0
